import type { Metadata } from "next";
import "./globals.css";
import { Pacifico, Poppins } from "next/font/google"
import Link from "next/link";

const fancyFont = Pacifico({ subsets: ['latin'], weight: ["400"] });
const plainFont = Poppins({ subsets: ['latin'], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={fancyFont.className}  >
          <header className={plainFont.className}>
            <div className="bg-orange-400 p-2">
              <h2 >
                <Link href="/home"className="collection"> Collection</Link>

                <Link href="/settings"  > Settings</Link>
              </h2>
            </div>
          </header>
          {children}
        </body>
      </html>
    </>
  );
}


